/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jokergamestats;

import java.text.DecimalFormat;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Iraklis Proviadakis and Thomas Gerodimos
 */



public class JFrame31 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame31
     */
    //Entity Manager & Controllers
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("JokergamePU");
    EntityManager em = emf.createEntityManager();
    EntityTransaction tx = em.getTransaction();
    
    public JFrame31() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(95, 95, 95))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
/*
        // Συχνότητας εμφάνισης αριθμών (πέντε πιο συχνά εμφανιζόμενοι αριθμοί)
        Query query = em.createNativeQuery("SELECT NUMBERS.N, SUM(NUMBERS.C) AS COUNT_TOTAL\n"
                + "FROM\n"
                + "(\n"
                + "SELECT NUMBER1 AS N, COUNT(NUMBER1) AS C FROM WINNINGNUMBERS GROUP BY NUMBER1\n"
                + "UNION ALL\n"
                + "SELECT NUMBER2 AS N, COUNT(NUMBER2) AS C FROM WINNINGNUMBERS GROUP BY NUMBER2\n"
                + "UNION ALL\n"
                + "SELECT NUMBER3 AS N, COUNT(NUMBER3) AS C FROM WINNINGNUMBERS GROUP BY NUMBER3\n"
                + "UNION ALL\n"
                + "SELECT NUMBER4 AS N, COUNT(NUMBER4) AS C FROM WINNINGNUMBERS GROUP BY NUMBER4\n"
                + "UNION ALL\n"
                + "SELECT NUMBER5 AS N, COUNT(NUMBER5) AS C FROM WINNINGNUMBERS GROUP BY NUMBER5\n"
                + ") NUMBERS\n"
                + "GROUP BY N\n"
                + "ORDER BY COUNT_TOTAL DESC FETCH FIRST 5 ROWS ONLY");
        
        //Πέρνω το αποτέλεσμα του query σε Object[]
        List<Object[]> list = query.getResultList();
        
        //Πίνακας για τους αριθμούς και την συχνότητα εμφάνισης
        Integer[] numbers = new Integer[5];
        Integer[] times = new Integer[5];
        
        //Διαπερνάω τα Object[] και καταχωρώ στους πίνακες numbers και times την πληροφορία
        int i = 0;//counter
        for (Object[] obj : list) {
            numbers[i] = (int) obj[0];
            times[i] = (int) obj[1];
            i++;
        }
        //System.out.println(Arrays.toString(numbers));
        
        //Δημιουργούμε model για τον πίνακα
        DefaultTableModel model = new DefaultTableModel();

        //Ορίζουμε τις επικεφαλίδες στον πίνακα και προσθέτουμε τους numbers και times στον jTable1
        model.setColumnIdentifiers(new String[]{"1oς Αριθμός", "2oς Αριθμός", "3oς Αριθμός", "4oς Αριθμός", "5oς Αριθμός"});
        model.addRow(numbers);
        model.addRow(times);
        jTable1.setModel(model);

        
        // Συχνότητα εμφάνισης αριθμών joker (πέντε πιο συχνά εμφανιζόμενοι αριθμοί)
        Query query2 = em.createNativeQuery("SELECT JOKER, COUNT(JOKER) AS C FROM WINNINGNUMBERS GROUP BY JOKER ORDER BY C DESC FETCH FIRST 5 ROWS ONLY");
        List<Object[]> list2 = query2.getResultList();
        
        //Πίνακας για τους αριθμούς και την συχνότητα εμφάνισης
        Integer[] numbers2 = new Integer[5];
        Integer[] times2 = new Integer[5];
        
        //Διαπερνάω τα Object[] και καταχωρώ στους πίνακες numbers και times την πληροφορία
        i = 0;
        for (Object[] obj : list2) {
            numbers2[i] = (int) obj[0];
            times2[i] = (int) obj[1];
            i++;
        }
        //System.out.println(Arrays.toString(numbers2));
        //Δημιουργούμε model για τον πίνακα
        DefaultTableModel model2 = new DefaultTableModel();

        //Ορίζουμε την επικεφαλίδα, εισάγουμε τους πίνακες numbers και times και ενημερώνουμε τον jTable2
        model2.setColumnIdentifiers(new String[]{"1oς Αριθμός", "2oς Αριθμός", "3oς Αριθμός", "4oς Αριθμός", "5oς Αριθμός"});
        model2.addRow(numbers2);
        model2.addRow(times2);
        jTable2.setModel(model2);

        
        //Μέσος όρος κερδών ανά κατηγορία
        
        //Καταχωρώ τα Prizecategories σε λία λίστα χρησημοποιώντας τον controller
        List<Prizecategories> categories = findPrizecategoriesEntities();
        
        //Αρχικοποιώ τον πίνακα με τα κέρδη ανά κατηγορία
        Double[] dividents = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
        i = 0;
        int mo = 0;//Μέσος όρος
        
        //Διαπερνάω τα Prizecategories και καταχωρώ στον πίνακα τα αθροίσματα κάθε κατηγορίας
        for (Prizecategories category : categories) {
            dividents[i] = dividents[i] + category.getDivident();
            i++;
            if (category.getId() == 7) {
                i = 0;
                mo++;
            }
        }

        //2 δεκαδικά και τελείες
        DecimalFormat df = new DecimalFormat("#,##0.00");
        
        //Υπολογισμός Μέσου όρου κερδών ανά κατηγορία
        String[] dividentsString = new String[8];
        for (int j = 0; j < dividents.length; j++) {
            dividentsString[j] = df.format(dividents[j] / mo);
        }

        //Δημιουργούμε model για τον πίνακα
        DefaultTableModel model3 = new DefaultTableModel();

        //Ορίζουμε την επικεφαλίδα, εισάγουμε τον πίνακα dividentsString και ενημερώνουμε τον jTable3
        model3.setColumnIdentifiers(new String[]{"5+1", "5", "4+1", "4", "3+1", "3", "2+1", "1+1"});
        model3.addRow(dividentsString);
        jTable3.setModel(model3);
        */
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
JokerStatsFrame jf3 = new JokerStatsFrame();  
        jf3.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame31.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame31.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame31.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame31.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame31().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
