package jokergamestats;

import java.awt.HeadlessException;
import java.io.IOException;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import org.json.JSONObject;
import static java.lang.Integer.parseInt;
import java.sql.Date;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import org.json.JSONArray;
import javax.persistence.Query;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import static jokergamestats.StartFrame.*;



/**
 *
 * @author Iraklis Proviadakis and Thomas Gerodimos
 */
public class JokerDataManagementFrame extends javax.swing.JFrame {
    
    //Δημιουργία απαραίτητων αντικειμένων όπου θα αποθηκευτούν τα στοιχεία που 
    //θα κατεβάσουμε με το API του OPAP
    private Games joker;
    private Winningnumbers CurrentWinningNumbers;
    private Draws CurrentDraw;
    private Prizecategories Prizecategories0;
    private Prizecategories Prizecategories1;
    private Prizecategories Prizecategories2;
    private Prizecategories Prizecategories3;
    private Prizecategories Prizecategories4;
    private Prizecategories Prizecategories5;
    private Prizecategories Prizecategories6;
    private Prizecategories Prizecategories7;

    
    public JokerDataManagementFrame() {
        initComponents();
        //Απόκρυψη των αντικειμένων πεδίων και τίτλων
        lblResultList.setVisible(false);
        lstDrawsFromSearch.setVisible(false);
        jLabel4.setVisible(true); 
         
        //Απόκρυψη πεδίου Joker 
         jTextField7.setVisible(true);
         
         //Απόκρυψη πεδίων αριθμών κλήρωσης
         jTextField2.setVisible(true);
         jTextField4.setVisible(true);
         jTextField5.setVisible(true);
         jTextField6.setVisible(true);
         jTextField3.setVisible(true);
         jTextField8.setVisible(false);
         lblDraw.setVisible(false);
         lblDrawDate.setVisible(false);
        
         //Αρχικοποίηση αντικειμένου Joker
        joker = new Games(5104,"Joker");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txbWinners7 = new javax.swing.JTextField();
        txbWinners8 = new javax.swing.JTextField();
        txbWinningsPerCategory2 = new javax.swing.JTextField();
        txbWinningsPerCategory3 = new javax.swing.JTextField();
        txbWinningsPerCategory4 = new javax.swing.JTextField();
        txbWinningsPerCategory5 = new javax.swing.JTextField();
        txbWinningsPerCategory6 = new javax.swing.JTextField();
        txbWinningsPerCategory7 = new javax.swing.JTextField();
        txbWinningsPerCategory8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txbCategory3 = new javax.swing.JTextField();
        txbProfits1 = new javax.swing.JTextField();
        txbWinners1 = new javax.swing.JTextField();
        txbWinningsPerCategory1 = new javax.swing.JTextField();
        txbCategory2 = new javax.swing.JTextField();
        txbProfits2 = new javax.swing.JTextField();
        txbCategory1 = new javax.swing.JTextField();
        txbCategory4 = new javax.swing.JTextField();
        txbCategory5 = new javax.swing.JTextField();
        txbCategory6 = new javax.swing.JTextField();
        txbCategory7 = new javax.swing.JTextField();
        txbCategory8 = new javax.swing.JTextField();
        txbProfits3 = new javax.swing.JTextField();
        txbProfits4 = new javax.swing.JTextField();
        txbProfits5 = new javax.swing.JTextField();
        txbProfits6 = new javax.swing.JTextField();
        txbProfits7 = new javax.swing.JTextField();
        txbProfits8 = new javax.swing.JTextField();
        txbWinners2 = new javax.swing.JTextField();
        txbWinners3 = new javax.swing.JTextField();
        txbWinners4 = new javax.swing.JTextField();
        txbWinners5 = new javax.swing.JTextField();
        txbWinners6 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnDeleteDraw = new javax.swing.JButton();
        txbDrawID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BtnSearch = new javax.swing.JButton();
        btnSaveNumbers = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txbDateFrom = new com.toedter.calendar.JDateChooser();
        txbDateTo = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        BtnGetRange = new javax.swing.JButton();
        BtnSaveAllDraws = new javax.swing.JButton();
        btnDeleteAll = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        lblDraw = new javax.swing.JLabel();
        lblDrawDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDrawsFromSearch = new javax.swing.JList<>();
        lblResultList = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setModalExclusionType(null);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ΔΙΑΧΕΙΡΙΣΗ ΔΕΔΟΜΕΝΩΝ ΤΖΟΚΕΡ");

        BtnBack.setText("Πίσω");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        txbWinners7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbWinners7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbWinners8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbWinners8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbWinningsPerCategory2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbWinningsPerCategory2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbWinningsPerCategory3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbWinningsPerCategory3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbWinningsPerCategory4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbWinningsPerCategory4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbWinningsPerCategory5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbWinningsPerCategory5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbWinningsPerCategory6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbWinningsPerCategory6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbWinningsPerCategory7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbWinningsPerCategory7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbWinningsPerCategory8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbWinningsPerCategory8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Διανεμόμενα");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Νικητές");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Κατηγορία");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Κέρδη ανά επιτυχία");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Πίνακας Κερδών");

        txbCategory3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbCategory3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbProfits1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbProfits1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbWinners1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbWinners1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbWinningsPerCategory1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbWinningsPerCategory1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbCategory2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbCategory2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbProfits2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbProfits2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbCategory1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbCategory1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbCategory4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbCategory4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbCategory5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbCategory5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbCategory6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbCategory6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbCategory7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbCategory7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbCategory8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbCategory8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbProfits3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbProfits3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbProfits4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbProfits4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbProfits5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbProfits5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbProfits6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbProfits6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbProfits7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbProfits7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbProfits8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbProfits8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbWinners2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbWinners2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbWinners3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbWinners3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbWinners4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbWinners4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbWinners5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbWinners5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txbWinners6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txbWinners6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(txbCategory6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(txbProfits6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(txbWinners6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(txbWinningsPerCategory6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txbCategory2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txbCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, 0)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txbProfits2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txbProfits1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, 0)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txbWinners1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txbWinners2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, 0)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txbWinningsPerCategory2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txbWinningsPerCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel7))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txbCategory3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txbProfits3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txbWinners3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txbWinningsPerCategory3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txbCategory4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txbProfits4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txbWinners4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txbWinningsPerCategory4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txbCategory5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txbProfits5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txbWinners5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txbWinningsPerCategory5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txbCategory8)
                    .addComponent(txbCategory7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txbProfits8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txbWinners8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txbWinningsPerCategory8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txbProfits7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txbWinners7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txbWinningsPerCategory7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbProfits1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbWinners1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbWinningsPerCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbProfits2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbWinners2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbWinningsPerCategory2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbCategory2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbCategory3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbProfits3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbWinners3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbWinningsPerCategory3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbCategory4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbProfits4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbWinners4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbWinningsPerCategory4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbCategory5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbProfits5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbWinners5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbWinningsPerCategory5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbWinners6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbWinningsPerCategory6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbCategory6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbProfits6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbProfits7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbWinners7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbWinningsPerCategory7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbCategory7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txbCategory8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txbProfits8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txbWinners8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txbWinningsPerCategory8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDeleteDraw.setText("Διαγραφή");
        btnDeleteDraw.setPreferredSize(new java.awt.Dimension(203, 23));
        btnDeleteDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDrawActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Παιχνιδιού:");

        BtnSearch.setText("Εμφάνιση");
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });

        btnSaveNumbers.setText("Αποθήκευση");
        btnSaveNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNumbersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txbDrawID, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteDraw, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txbDrawID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSearch)
                    .addComponent(btnSaveNumbers)
                    .addComponent(btnDeleteDraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jLabel3.setText("Από:");

        jLabel4.setText("'Εως:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txbDateFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(txbDateTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txbDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txbDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnGetRange.setText("Εύρεση");
        BtnGetRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGetRangeActionPerformed(evt);
            }
        });

        BtnSaveAllDraws.setText("Αποθήκευση των αποτελεσμάτων");
        BtnSaveAllDraws.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveAllDrawsActionPerformed(evt);
            }
        });

        btnDeleteAll.setText("Διαγραφή δεδομένων εντός εύρους");
        btnDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAllActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\JokerGameStats\\images\\info.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDeleteAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnSaveAllDraws, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(BtnGetRange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnGetRange)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnSaveAllDraws)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteAll)
                .addContainerGap())
        );

        jTextField3.setBackground(new java.awt.Color(16, 76, 140));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 195, 20));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setCaretColor(new java.awt.Color(255, 195, 20));

        jTextField6.setBackground(new java.awt.Color(255, 195, 20));
        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(16, 76, 140));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Νικήτρια Στήλη");

        jTextField5.setBackground(new java.awt.Color(255, 195, 20));
        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(16, 76, 140));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField4.setBackground(new java.awt.Color(255, 195, 20));
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(16, 76, 140));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField7.setBackground(new java.awt.Color(255, 195, 20));
        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(16, 76, 140));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField2.setBackground(new java.awt.Color(255, 195, 20));
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(16, 76, 140));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel6)
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lblDraw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDraw.setText("Αριθμός Κλήρωσης");

        lblDrawDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDrawDate.setText("Ημερομηνία");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDraw)
                    .addComponent(lblDrawDate))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDraw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lblDrawDate)
                .addContainerGap())
        );

        lstDrawsFromSearch.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstDrawsFromSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstDrawsFromSearchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstDrawsFromSearch);

        lblResultList.setText("Αποτελέσματα");

        jTextField8.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 58, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BtnBack)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(lblResultList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(lblResultList)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnBack))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void GetDrawData() {
        //  Μέθοδος με την οποία πέρνουμε στοιχεία με το API του ΟΠΑΠ      
        String urlToCall = "https://api.opap.gr/draws/v3.0/" + joker.getGameid() + "/" + txbDrawID.getText();
        OkHttpClient client = new OkHttpClient();
        Request request = new Request.Builder().url(urlToCall).build();
        
        //Αποθήκευση του αποτελέσματος της κλήσης σε αντικείμενο τύπου Response
        try (Response response = client.newCall(request).execute()) {
            if (response.isSuccessful() && response.body() != null) {
                //Αν το API call είναι επιτυχές αποθηκευω το αποτέλεσμα σε ενα string
                String responseString = response.body().string();

                //Παίρνω το αποτέλεσμα σε αντικείμενο JSON απο το String
                JSONObject j0 = new JSONObject(responseString);

                //Παίρνω απο το αντικείμενο JSON τον κωδικό της κλήρωσης
                String drawId = j0.optString("drawId");

                //Παίρνω απο το αντικείμενο JSON την ημερομηνία και ώρα της κλήρωσης
                String drawTime = j0.optString("drawTime");

                //Μετατρέπω σε ημερομηνία (με format yyyy-mm-dd) το timestamp
                long drawTimeLong = Long.parseLong(drawTime);
                Date drawTimeDate = new Date(drawTimeLong);

                //Δημιουργία αντικειμένου κλήρωση
                CurrentDraw = new Draws();
                CurrentDraw.setDrawsPK(new DrawsPK(parseInt(drawId), joker.getGameid()));
                CurrentDraw.setDrawdate(drawTimeDate);

                //Παίρνω απο το αντικείμενο JSON του αριθμούς που κληρώθηκαν
                String winningNumbersStr = j0.getJSONObject("winningNumbers").toString();
                JSONObject j1 = new JSONObject(winningNumbersStr);

                //Δημιουργία αντικειμένου Κληρωθέντες αριθμοί
                CurrentWinningNumbers = new Winningnumbers();
                CurrentWinningNumbers.setDrawid(CurrentDraw.drawsPK.getDrawid());
                
                //Παίρνω απο το αντικείμενο JSON τον αριθμό Joker
                JSONArray bonus = j1.optJSONArray("bonus");
                String jokerInt = Integer.toString(bonus.getInt(0));
                //Αποθήκευση του Joker
                CurrentWinningNumbers.setBonus(parseInt(jokerInt));

                //Εμφάνιση του αριθμου της κλήρωσης στην φόρμα
                lblDraw.setVisible(true);
                lblDraw.setText("Κλήρωση " + CurrentDraw.drawsPK.getDrawid());

                //Εμφάνιση της ημερομηνίας της κλήρωσης στην φόρμα
                lblDrawDate.setVisible(true);
                lblDrawDate.setText("Ημερομηνία: " + CurrentDraw.getDrawdate());

                CurrentWinningNumbers.setDrawsgameid(joker.getGameid());
                
                //Εμφάνιση τίτλου "Νικήτρια Στηλη"
                jLabel4.setVisible(true);

                //Show Joker number
                jTextField3.setText(CurrentWinningNumbers.getBonus().toString());
                jTextField3.setVisible(true);

                //Διάβασμα αριθμών απο το Json Array
                JSONArray list = j1.optJSONArray("list");
                
                //Διαβάζουμε κάθε αριθμό, τον αποθηκεύουμε στο αντικειμενο που φτιάξαμε και τον εμφανιζουμε στην φόρμα
                for (int i = 0; i < list.length(); i++) {
                    switch (i) {
                        case 0:
                            // code block
                            CurrentWinningNumbers.setNumber1(list.getInt(i));
                            jTextField2.setText(CurrentWinningNumbers.getNumber1().toString());
                            jTextField2.setVisible(true);
                            break;
                        case 1:
                            // code block
                            CurrentWinningNumbers.setNumber2(list.getInt(i));
                            jTextField4.setVisible(true);
                            jTextField4.setText(CurrentWinningNumbers.getNumber2().toString());
                            break;
                        case 2:
                            // code block
                            CurrentWinningNumbers.setNumber3(list.getInt(i));
                            jTextField5.setVisible(true);
                            jTextField5.setText(CurrentWinningNumbers.getNumber3().toString());
                            break;
                        case 3:
                            // code block
                            CurrentWinningNumbers.setNumber4(list.getInt(i));
                            jTextField6.setVisible(true);
                            jTextField6.setText(CurrentWinningNumbers.getNumber4().toString());
                            break;
                        case 4:
                            // code block
                            CurrentWinningNumbers.setNumber5(list.getInt(i));
                            jTextField7.setVisible(true);
                            jTextField7.setText(CurrentWinningNumbers.getNumber5().toString());
                            break;
                        default:
                            jTextField8.setVisible(true);
                            jTextField8.setText("Something happened with the API Call. Please contact Administrator!");

                    }
                }
                
                //Διαβάζουμε τις κατηγορίες κερδών απο το Json Array
                String prizeCategories = j0.optJSONArray("prizeCategories").toString();
                JSONArray jsonarray = new JSONArray(prizeCategories);

                //Διαβάζουμε κάθε αντικειμένο και τα εμφανιζουμε στην φόρμα
                for (int i = 0; i < jsonarray.length(); i++) {
                    JSONObject jsonobject = jsonarray.getJSONObject(i);
                    
                    //Prize Category ID 
                    String id = jsonobject.optString("id");

                    //Jackpot
                    String jackpot = jsonobject.optString("jackpot");
                    String distributed = jsonobject.optString("distributed");

                    Float Payments = Float.parseFloat(jackpot) + Float.parseFloat(distributed);

                    //Επιτυχίες
                    String winners = jsonobject.optString("winners");

                    //Επιτυχίες
                    String dividentString = jsonobject.optString("divident");
                    Float divident = Float.parseFloat(dividentString);

                    //Μορφοποίηση οικονομικών στοιχείων σε νόμισμα
                    NumberFormat nf = NumberFormat.getCurrencyInstance();
                    
                    //Για κάθε αντικείμενο του Json Array τα εμφανίζουμε στην οθόνη και 
                    //τα αποθηκεύουμε στα αντίστοιχα αντικείμενα
                    switch (i) {
                        case 0:
                            txbCategory1.setText("5+1");
                            txbProfits1.setText(nf.format(Payments));
                            txbWinners1.setText(winners);
                            if (divident == 0.00) {
                                txbWinningsPerCategory1.setText("ΤΖΑΚ-ΠΟΤ");
                            } else {
                                txbWinningsPerCategory1.setText(nf.format(divident));
                            }
                            Prizecategories0 = new Prizecategories();
                            Prizecategories0.setPrizecategoriesPK(new PrizecategoriesPK(CurrentDraw.drawsPK.getDrawid(), "5+1"));
                            Prizecategories0.setDrawsgameid(CurrentDraw.drawsPK.getDrawid());
                            Prizecategories0.setDrawsgameid(joker.getGameid());
                            Prizecategories0.setProfitpercategory(divident);
                            Prizecategories0.setProfits(Payments);
                            Prizecategories0.setWinners(parseInt(winners));
                            break;
                        case 1:
                            txbCategory2.setText("5");
                            txbProfits2.setText(nf.format(Payments));
                            txbWinners2.setText(winners);
                            txbWinningsPerCategory2.setText(nf.format(divident));
                            Prizecategories1 = new Prizecategories();
                            Prizecategories1.setPrizecategoriesPK(new PrizecategoriesPK(CurrentDraw.drawsPK.getDrawid(), "5"));
                            Prizecategories1.setDrawsgameid(CurrentDraw.drawsPK.getDrawid());
                            Prizecategories1.setDrawsgameid(joker.getGameid());
                            Prizecategories1.setProfitpercategory(divident);
                            Prizecategories1.setProfits(Payments);
                            Prizecategories1.setWinners(parseInt(winners));
                            break;
                        case 2:
                            txbCategory3.setText("4+1");
                            txbProfits3.setText(nf.format(Payments));
                            txbWinners3.setText(winners);
                            txbWinningsPerCategory3.setText(nf.format(divident));
                            Prizecategories2 = new Prizecategories();
                            Prizecategories2.setPrizecategoriesPK(new PrizecategoriesPK(CurrentDraw.drawsPK.getDrawid(), "4+1"));
                            Prizecategories2.setDrawsgameid(CurrentDraw.drawsPK.getDrawid());
                            Prizecategories2.setDrawsgameid(joker.getGameid());
                            Prizecategories2.setProfitpercategory(divident);
                            Prizecategories2.setProfits(Payments);
                            Prizecategories2.setWinners(parseInt(winners));
                            break;
                        case 3:
                            txbCategory4.setText("4");
                            txbProfits4.setText(nf.format(Payments));
                            txbWinners4.setText(winners);
                            txbWinningsPerCategory4.setText(nf.format(divident));
                            Prizecategories3 = new Prizecategories();
                            Prizecategories3.setPrizecategoriesPK(new PrizecategoriesPK(CurrentDraw.drawsPK.getDrawid(), "4"));
                            Prizecategories3.setDrawsgameid(CurrentDraw.drawsPK.getDrawid());
                            Prizecategories3.setDrawsgameid(joker.getGameid());
                            Prizecategories3.setProfitpercategory(divident);
                            Prizecategories3.setProfits(Payments);
                            Prizecategories3.setWinners(parseInt(winners));
                            break;
                        case 4:
                            txbCategory5.setText("3+1");
                            txbProfits5.setText(nf.format(Payments));
                            txbWinners5.setText(winners);
                            txbWinningsPerCategory5.setText(nf.format(divident));
                            Prizecategories4 = new Prizecategories();
                            Prizecategories4.setPrizecategoriesPK(new PrizecategoriesPK(CurrentDraw.drawsPK.getDrawid(), "3+1"));
                            Prizecategories4.setDrawsgameid(CurrentDraw.drawsPK.getDrawid());
                            Prizecategories4.setDrawsgameid(joker.getGameid());
                            Prizecategories4.setProfitpercategory(divident);
                            Prizecategories4.setProfits(Payments);
                            Prizecategories4.setWinners(parseInt(winners));
                            break;
                        case 5:
                            txbCategory6.setText("3");
                            txbProfits6.setText(nf.format(Payments));
                            txbWinners6.setText(winners);
                            txbWinningsPerCategory6.setText(nf.format(divident));
                            Prizecategories5 = new Prizecategories();
                            Prizecategories5.setPrizecategoriesPK(new PrizecategoriesPK(CurrentDraw.drawsPK.getDrawid(), "3"));
                            Prizecategories5.setDrawsgameid(CurrentDraw.drawsPK.getDrawid());
                            Prizecategories5.setDrawsgameid(joker.getGameid());
                            Prizecategories5.setProfitpercategory(divident);
                            Prizecategories5.setProfits(Payments);
                            Prizecategories5.setWinners(parseInt(winners));
                            break;
                        case 6:
                            txbCategory7.setText("2+1");
                            txbProfits7.setText(nf.format(Payments));
                            txbWinners7.setText(winners);
                            txbWinningsPerCategory7.setText(nf.format(divident));
                            Prizecategories6 = new Prizecategories();
                            Prizecategories6.setPrizecategoriesPK(new PrizecategoriesPK(CurrentDraw.drawsPK.getDrawid(), "2+1"));
                            Prizecategories6.setDrawsgameid(CurrentDraw.drawsPK.getDrawid());
                            Prizecategories6.setDrawsgameid(joker.getGameid());
                            Prizecategories6.setProfitpercategory(divident);
                            Prizecategories6.setProfits(Payments);
                            Prizecategories6.setWinners(parseInt(winners));
                            break;
                        case 7:
                            txbCategory8.setText("1+1");
                            txbProfits8.setText(nf.format(Payments));
                            txbWinners8.setText(winners);
                            txbWinningsPerCategory8.setText(nf.format(divident));
                            Prizecategories7 = new Prizecategories();
                            Prizecategories7.setPrizecategoriesPK(new PrizecategoriesPK(CurrentDraw.drawsPK.getDrawid(), "1+1"));
                            Prizecategories7.setDrawsgameid(CurrentDraw.drawsPK.getDrawid());
                            Prizecategories7.setDrawsgameid(joker.getGameid());
                            Prizecategories7.setProfitpercategory(divident);
                            Prizecategories7.setProfits(Payments);
                            Prizecategories7.setWinners(parseInt(winners));
                            break;
                        default:
                            jTextField8.setVisible(true);
                            jTextField8.setText("Something happened with the API Call. Please contact Administrator!");
                    }

                }

            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Παρουσιάστηκε κάποιο πρόβλημα. Παρακαλώ επικοινωνήστε με τοιν διαχειριστή!");
        }
    }
    
    //Μέθοδος που αποθηκεύει στην Βάση Δεδομένων
    public void SaveDrawToDB(boolean RootMessageShow) {
        //Δημιουργία αντικειμένων EntityManagerFactory και EntityManager
        StartFrame.createEMFandEM();
        
        Query query1 = em.createQuery("SELECT count(s) FROM Games s");
        long count = (long) query1.getSingleResult();
        //Αν δεν υπάρχει καταχωρημένο το παιχνίδι Joker στον πίνακα των Games αποθηκευσε το αντικείμενο 
        //Joker που έχει δημιουρηθεί
        if (count == 0) {
            em.getTransaction().begin();
            try {
                em.persist(joker);
                em.getTransaction().commit();
            } catch (HeadlessException e) {
                //Αν παρουσιαστεί κάποιο πρόβλημα ακύρωσε τo transaction 
                em.getTransaction().rollback();
            } 

        }
        
        //Δημιούργησε ενα transaction για αποθηκευση τω νστοιχείων στην Βάση Δεδομένων
        em.getTransaction().begin();
        try {
            //Αποθήκευση της τρέχουσας κλήρωσης
            em.persist(CurrentDraw);
            //Αποθήκευση των αριθμών που κερδίζουν
            em.persist(CurrentWinningNumbers);
            //Αποθήκευση των κατηγοριών κερδών
            em.persist(Prizecategories0);
            em.persist(Prizecategories1);
            em.persist(Prizecategories2);
            em.persist(Prizecategories3);
            em.persist(Prizecategories4);
            em.persist(Prizecategories5);
            em.persist(Prizecategories6);
            em.persist(Prizecategories7);
            em.getTransaction().commit();
            //Αν η μέθοδος έχει κληθεί με παράμετρο true δείξε ετο μήνυμα επιτυχίας
            //Αυτό μπήκε γιατί στην περίπτωση που θα αποθηκεύει πολλές κληρώσεις θα εμφάνιζε πολλές φορές το μήνυμα και 
            //θα χρειάζοτανε η παρέμβαση του χρήστη για να συνεχιστεί η διαδικασία
            if (RootMessageShow == true) {
                JOptionPane.showMessageDialog(this, "Τα στοιχεία της κλήρωσης αποθηκεύτηκαν κανονικά!");
            }
        } catch (Exception e) {
              if (RootMessageShow == true) {
            JOptionPane.showMessageDialog(this, "Τα στοιχεία της κλήρωσης είναι ήδη αποθηκευμένα!");
              }
            em.getTransaction().rollback();
        } finally{
            //Με την ολοκλήρωση της διαδικασίας κλείνουμε τα αντικείμενα
            em.close();
            emf.close();        
    }

    }

    //Διαγραφή απο την Βάση Δεδομένων
    public void DeleteFromDB(boolean RootMessageShow) {
        //Δημιουργία αντικειμένων EntityManagerFactory και EntityManager
        StartFrame.createEMFandEM();

        em.getTransaction().begin();
        try {
            //Διαγραφή επιλεγμένης κλήρωσης
            Query query1 = em.createNamedQuery("Draws.DeleteByDrawid");
            query1.setParameter("drawid", parseInt(txbDrawID.getText()));
            query1.executeUpdate();

            //Διαγραφή των αριθμών της κλήρωσης
            Query query2 = em.createNamedQuery("Winningnumbers.deleteByDrawid");
            query2.setParameter("drawid", parseInt(txbDrawID.getText()));
            query2.executeUpdate();

            //Διαγραφή τω νκερδών της κλήρωσης
            Query query3 = em.createNamedQuery("Prizecategories.deleteByDrawid");
            query3.setParameter("drawid", parseInt(txbDrawID.getText()));
            query3.executeUpdate();

            em.getTransaction().commit();
            //Αν η μέθοδος έχει κληθεί με παράμετρο true δείξε το μήνυμα 
            //Αυτό μπήκε γιατί στην περίπτωση που θα διαγράφει πολλές κληρώσεις θα εμφάνιζε πολλές φορές το μήνυμα και 
            //θα χρειάζοτανε η παρέμβαση του χρήστη για να συνεχιστεί η διαδικασία
            if (RootMessageShow == true) {
                JOptionPane.showMessageDialog(this, "Τα στοιχεία της κλήρωσης διαγράφηκαν!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Αποτυχία διαγραφής δεδομένων κλήρωσης!");
            em.getTransaction().rollback();
        }
        em.close();
        emf.close();
        
    }
    
    
    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        
        //Πατώντας το κουμπι πισω μας πηγαίνει στην αρχική οθόνη
        StartFrame jf0 = new StartFrame();
        jf0.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed
        // Εμφάνιση των δεδομένων της κλήρωσης που έχει συμπληρώσει ο χρήστης στο 
        //αντίστοιχο πεδίο με κλήση στην αντίστοιχη μέθοδο
        GetDrawData();
    }//GEN-LAST:event_BtnSearchActionPerformed

    private void btnSaveNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNumbersActionPerformed
       // Αποθήκευση των δεδομένων της κλήρωσης που έχει επιστρέψει η αναζήτηση 
       //με κλήση στην αντίστοιχη μέθοδο
        SaveDrawToDB(true);          
    }//GEN-LAST:event_btnSaveNumbersActionPerformed

    //Εμφάνιση λίστας κληρώσεων που είναι σε ένα ευρος ημερομηνιών
    DefaultListModel mod = new DefaultListModel();
    private void BtnGetRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGetRangeActionPerformed
        lblResultList.setVisible(true);
        lstDrawsFromSearch.setVisible(true);
        lstDrawsFromSearch.setModel(mod);
        //Καθαρισμός λίστας απο προηγούμενη αναζήτηση (αν υπάρχουν)
        mod.clear();
        //Μορφοποίηση ημερομηνίας
        String pattern = "yyyy-MM-dd";
        DateFormat simpleDateFormat = new SimpleDateFormat(pattern);
        
        //Φόρτωση δεδομένων
        
        String urlToCall = "https://api.opap.gr/draws/v3.0/5104/draw-date/" + simpleDateFormat.format(txbDateFrom.getDate()) + "/" + simpleDateFormat.format(txbDateTo.getDate()) + "/draw-id";
        OkHttpClient client2 = new OkHttpClient();
        Request request2 = new Request.Builder().url(urlToCall).build();

        try (Response response2 = client2.newCall(request2).execute()) {
            if (response2.isSuccessful() && response2.body() != null) {
                //Parse Json from API

                String responseString2 = response2.body().string();

                String[] items = responseString2.replaceAll("\\[", "").replaceAll("\\]", "").replaceAll("\\s", "").split(",");
                int[] results = new int[items.length];
                //Αποθήκευση αριθμού κλήρωσης στην λίστα
                for (int i = 0; i < items.length; i++) {
                    try {
                        results[i] = Integer.parseInt(items[i]);
                        //Add Item
                        mod.addElement(results[i]);

                    } catch (NumberFormatException nfe) {
                        JOptionPane.showMessageDialog(this, "Παρουσιάστηκε κάποιο πρόβλημα. Παρακαλώ επικοινωνήστε με τοιν διαχειριστή!");
                    }
                }

            }
        } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Παρουσιάστηκε κάποιο πρόβλημα. Παρακαλώ επικοινωνήστε με τοιν διαχειριστή!");
        }
    }//GEN-LAST:event_BtnGetRangeActionPerformed

    private void btnDeleteDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDrawActionPerformed
        // Κλήση της μεθόδου που κάνει διαγραφή της τρέχουσας κλήρωσης με επιλογή προβολής μηνύματος.
        DeleteFromDB(true);
    }//GEN-LAST:event_btnDeleteDrawActionPerformed

    private void lstDrawsFromSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstDrawsFromSearchMouseClicked
        // Με διπλό κλικ φορτώνει της συγκεκριμένη κλήρωση στην οθόνη 
        if (evt.getClickCount() == 2) {
            int index = lstDrawsFromSearch.locationToIndex(evt.getPoint());
            if (index >= 0) {
                Object o = lstDrawsFromSearch.getModel().getElementAt(index);
                txbDrawID.setText(o.toString());
                GetDrawData();
            }
        }
    }//GEN-LAST:event_lstDrawsFromSearchMouseClicked

    private void btnDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAllActionPerformed
        // Διαγραφή όλων των κληρώσεων
        ListModel model = lstDrawsFromSearch.getModel();

        for (int i = 0; i < model.getSize(); i++) {
            Object o = model.getElementAt(i);
            txbDrawID.setText(o.toString());
            GetDrawData();
            DeleteFromDB(false);
        }
        JOptionPane.showMessageDialog(this, "Όλα τα δεδομένα διαγράφηκαν!");
        
    }//GEN-LAST:event_btnDeleteAllActionPerformed

    private void BtnSaveAllDrawsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveAllDrawsActionPerformed
        // Αποθήκευση όλων των κληρώσεων
        ListModel model = lstDrawsFromSearch.getModel();

        for (int i = 0; i < model.getSize(); i++) {
            Object o = model.getElementAt(i);
            txbDrawID.setText(o.toString());
            GetDrawData();
            SaveDrawToDB(false);
        }
        JOptionPane.showMessageDialog(this, "Όλα τα δεδομένα αποθηκεύτηκαν!");
    }//GEN-LAST:event_BtnSaveAllDrawsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Ενημερωτικό μήνυμα προς τον χρήστη
        JOptionPane.showMessageDialog(this, "Με διπλό κλικ στον αριθμό της κλήρωσης μπορείτε να φορτώσετε τα δεδομένα!");      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JokerDataManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JokerDataManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JokerDataManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JokerDataManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JokerDataManagementFrame().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnGetRange;
    private javax.swing.JButton BtnSaveAllDraws;
    private javax.swing.JButton BtnSearch;
    private javax.swing.JButton btnDeleteAll;
    private javax.swing.JButton btnDeleteDraw;
    private javax.swing.JButton btnSaveNumbers;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblDraw;
    private javax.swing.JLabel lblDrawDate;
    private javax.swing.JLabel lblResultList;
    private javax.swing.JList<String> lstDrawsFromSearch;
    private javax.swing.JTextField txbCategory1;
    private javax.swing.JTextField txbCategory2;
    private javax.swing.JTextField txbCategory3;
    private javax.swing.JTextField txbCategory4;
    private javax.swing.JTextField txbCategory5;
    private javax.swing.JTextField txbCategory6;
    private javax.swing.JTextField txbCategory7;
    private javax.swing.JTextField txbCategory8;
    private com.toedter.calendar.JDateChooser txbDateFrom;
    private com.toedter.calendar.JDateChooser txbDateTo;
    private javax.swing.JTextField txbDrawID;
    private javax.swing.JTextField txbProfits1;
    private javax.swing.JTextField txbProfits2;
    private javax.swing.JTextField txbProfits3;
    private javax.swing.JTextField txbProfits4;
    private javax.swing.JTextField txbProfits5;
    private javax.swing.JTextField txbProfits6;
    private javax.swing.JTextField txbProfits7;
    private javax.swing.JTextField txbProfits8;
    private javax.swing.JTextField txbWinners1;
    private javax.swing.JTextField txbWinners2;
    private javax.swing.JTextField txbWinners3;
    private javax.swing.JTextField txbWinners4;
    private javax.swing.JTextField txbWinners5;
    private javax.swing.JTextField txbWinners6;
    private javax.swing.JTextField txbWinners7;
    private javax.swing.JTextField txbWinners8;
    private javax.swing.JTextField txbWinningsPerCategory1;
    private javax.swing.JTextField txbWinningsPerCategory2;
    private javax.swing.JTextField txbWinningsPerCategory3;
    private javax.swing.JTextField txbWinningsPerCategory4;
    private javax.swing.JTextField txbWinningsPerCategory5;
    private javax.swing.JTextField txbWinningsPerCategory6;
    private javax.swing.JTextField txbWinningsPerCategory7;
    private javax.swing.JTextField txbWinningsPerCategory8;
    // End of variables declaration//GEN-END:variables
}
